name: godoshire_servidor
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/matheusoreis/Godoshire

environment:
  sdk: ^3.2.3

dependencies:
  ansicolor: ^2.0.2
  pocketbase: ^0.18.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
